#import "../book.typ": *

#show: book-page.with(
  title: "1.4 Construct of Measures"
)

== Construct of Measures

#definition[
Let $cal(A) subset cal(P) (X)$ be an algebra.
A function $mu_0: cal(A) -> [0, +infinity]$ is a premeasure iff

- $mu_0(#sym.emptyset.rev) = 0$,
- if ${A_j }_1^infinity subset.eq cal(A)$ is disjoint
  s.t. $union.big.sq_1^infinity A_i in cal(A)$, then $mu_0 (union.big.sq_1^infinity A_i) = sum_(i=1)^(infinity) mu_0 (A_i)$.

]

The goal of this section is to start
from $(X, cal(A), mu_0)$ to construct a measure on $sigma (cal(A))$
that extends $mu_0$.

#definition[
An outer measure on $X$ is a function $mu^*: cal(P) -> [0, +infinity]$
s.t.

- $mu^* (diameter) = 0$,
- $mu^* (A) <= mu^*(B)$ if $A subset.eq B$,
- $sigma$-subadditivity: $mu^* (union.big _1^infinity A_j) <= sum_1^infinity mu^*(A_j)$.

]

It arises from approximately a set of "from the outside".

#proposition[
Let $(X, cal(A), mu_0)$ be a premeasure space, then $forall E in X$,
$
mu^*(E) := inf{sum_(j=1)^infinity mu_0(A_j): A_j in cal(A), union.big _(j=1)^infinity A_j supset E}
$
defines an outer measure.
]<prp:1.4.1>

#definition[
Say $A subset X$ satisfies separation condition [C] of Caratheodory iff
$
mu^*(E) = mu^*(E inter A) + mu^*(E without A), forall E subset X
$
where $mu^*$ is an outer measure.

]

For a set $A subset cal(P)(X)$ satisfying separation condition [C], we also call it $mu^*$-measurable.

#theorem(title: "Caratheodory's Theorem")[
Let $mu^*$ be an outer measure on $X$. Then 
$
cal(F) := {A subset X: mu^*(E) = mu^*(E inter A) + mu^*(E without A), forall E subset X}
$
is a $sigma$-algebra, and $mu^*|_cal(F)$ is a complete measure.
]

#theorem[
Let $cal(A) subset cal(P) (X)$ be an algebra, $mu_0$ a premeasure on $cal(A)$, and $sigma(cal(A))$ the $sigma$-algebra generated by $cal(A)$. There exists a measure $mu$ on $sigma(cal(A))$ whose restriction to $cal(A)$ is $mu_0$ - namely, $mu = mu^(*) |_sigma(cal(A))$ where $mu^(*)$ is given by @prp:1.4.1. If $nu$ is another measure on $sigma(cal(A))$ that extends $mu_0$,then $nu (E) lt.eq mu (E)$ for all $E in sigma(cal(A))$, with equality when $mu (E) < oo$. If $mu_0$ is $sigma$-finite,then $mu$ is the unique extension of $mu_0$ to a measure on $sigma(cal(A))$.
]