#import "/book.typ": book-page
#import "../../../templates/conf.typ": *
#show: thmrules.with(qed-symbol: $square$)

#show: book-page.with(title: "Sigma Algebra")


= $sigma$-algebra

#def[
  Let $X eq.not diameter$ be a set.
  1. $cal(A) subset cal(P) (X)$ is an algebra if it is closed under finite unions and complement; in others words, if $E_1 , dots.h , E_n in cal(A)$ , then $union.big_1^n E_j in cal(A)$ ; and if $E in cal(A)$, then $E^c in cal(A)$ .
  2. An algebra is a $sigma$-algebra if it is also closed under countable unions.
]

In 2 one can replace "countable unions" by disjoint countable unions, since
  $ sum_(k = 1)^oo E_k = union.sq.big_(k = 1)^oo tilde(E_k) , $
  where $tilde(E_1) = E_1 , tilde(E_2) = E_2 \\ E_1 , tilde(E_n) = E_n \\ (E_1 union E_2 dots.h union E_(n - 1))$ . 

#exm[
  0. $cal(P) (X)$, and ${ diameter , X }$ are $sigma$-algebra.
  1. If $X$ is uncountable, $ cal(F) := { E subset X : E thin upright("or") thin E^c thin upright("is countable") } $ (The point here is that if ${ E_j }_1^n in cal(F)$ , then $union.big_1^oo E_j$ is countable if all $E_j$ are countable and is co-countable otherwise.)
  2. ${ cal(F)_i }_(i in I)$ are $sigma$-algebra, $I$ is any indexing set, then $sect.big_(i in I) cal(F)_i$ is $sigma$-algebra.
  3. Let $cal(E) subset cal(P) (X)$ be arbitrary, then $ sigma (cal(E)) := sect.big { cal(F) subset cal(P) (X) : cal(F) supset cal(E) }, $ is the smallest $sigma$-algebra on $X$ containing $cal(E)$ , where $cal(F)$ is a $sigma$-algebra.
]

#def[
  $sigma (cal(E))$ is called the $sigma$-algebra generated by $cal(E)$ .
]

#prp[
  Let $cal(E)_1 subset cal(P) (X)$ be arbitrary and let $cal(E)_2 subset sigma (cal(E)_1)$ , then $sigma (cal(E)_2) subset sigma (cal(E))_1$ .
]

#prf[
  Since $sigma (cal(E)_1)$ is a $sigma$-algebra containing $cal(E)_2$ , it therefore contains $sigma (cal(E)_2)$ .
]



Recall: $cal(T) = { O in cal(P) (X) : O thin upright("is open") }$ .

#def[
  Let $(X , cal(T))$ be a topological space, then $sigma (cal(T)) equiv cal(B)_X$ is the Bozel $sigma$-algebra on $(X , cal(T))$ .
]

#prp[
  On $bb(R) = bb(R)^1$ equipped with the Euclidean topology,
  $ cal(B)_(bb(R)) = sigma (cal(A)_i) $ for any $i in { 1 , dots.h , 5 }$
  1. open finite intervals: $cal(A)_1 = { (a , b) : a < b }$ ,
  2. closed finite intervals: $cal(A)_2 = { [a , b] : a < b }$ ,
  3. half- open finite intervals: $cal(A)_3 = { \( a , b \] : a < b }$ , or $cal(A)_3 = { \[ a , b \) : a < b }$ ,
  4. open, semi-infinite intervals: $cal(A)_4 = { (a , + oo) }$ , or $cal(A)_4 = { (- oo , a) }$ ,
  5. closed, semi-infinite intervals: $cal(A)_5 = { \[ a , + oo \) }$ , or $cal(A)_5 = { \( - oo , a \] }$ .
]



$cal(B)_(bb(R)^n) = cal(B)_(bb(R)) times dots.h times cal(B)_(bb(R))$ ?

Here we follow: G Folland, Real Analysis.

#def[
  Let ${ X_i }_(i in I)$ be nonempty sets, $I$ is arbitrary. Let
  $X := product_(i in I) X_i$ be the Cartesian product. Let $cal(F)_i$ be
  a $sigma$-algebra on $X_i$ for each $i in I$ . Donate the coordinate map
  $pi_j : X arrow.r X_j , { x_j }_(i in I) arrow.r x_j$ , then the product
  of $sigma$-algebra on $X$ is
  $ times.circle.big cal(F)_i := sigma ({ pi_i^(- 1) (E_i) : E_i subset cal(F)_i , i in I }) $
]



Note: for countable $I$ , $pi_i^(- 1) (E_i) = X times X times dots.h times E_i times X times dots.h$ , where $E_i$ is the i-th.

#rmk[
  For countable $I$ , $times.circle.big_(i = 1)^oo cal(F)_i = sigma {product_(i = 1)^oo E_i : E_i in cal(F)_i}$
]

#prp[
  Consider ${ cal(F)_i }_(i in I)$ , where $cal(F)_i = sigma (cal(E)_i)$ ,
  then
  $ times.circle.big_(i in I) cal(F) = sigma (hat(cal(E))) , hat(cal(E)) = { pi_i^(- 1) (E_i) : E_i in cal(E)_i , i in I } . $
]

#prf[
  By the def of product on $sigma$-algebra,
  $ sigma (hat(cal(E))) subset times.circle.big_(i in I) cal(F)_i , $
  Conversely, for each $i in I$, consider
  $ cal(G)_i := { A subset X_i : pi_i^(- 1) (A) in sigma (hat(cal(E))) } . $
  Clearly, $cal(G)_i$ is a $sigma$-algebra on $X_i$ , and
  $cal(G)_i supset cal(E)_i$ :
  
  indead, for any $A in cal(E)_i$ , we have
  $ pi_i^(- 1) (A) in hat(cal(E))_i subset sigma (hat(cal(E))) . $
  Hence,
  $cal(G)_i supset sigma (cal(E)_i) = cal(F)_i$ . That is ,
  $pi_i^(- 1) (E) in sigma (hat(cal(E)))$ for each
  $i in I , E in cal(F)_i$ . Thus,
  $times.circle.big cal(F)_i subset sigma (hat(cal(E)))$ .
]

#prp[
  Let $X_1 , dots.h , X_n$ be metric spaces. Let
  $X = X_1 times dots.h times X_n$, then
  $
  cal(B)_X supset.eq times.circle.big_(j = 1)^n cal(B)_(X_j) .
  $
  Equality holds whenever $X_j$ are seperable.
]

#prf[
  By the previous proposition,
  $ times.circle.big_(j = 1)^n cal(B)_(X_j) = sigma ({ pi_j^(- 1) (U_j) , U_j subset X_j thin upright("is open") , j = 1 , dots.h , n }) . $

  But $pi_j^(- 1) (U_j)$ is open in $X$ , so
  $times.circle.big cal(B)_(X_j) subset.eq cal(B)_X$ .
  
  Suppose now that
  $X_j$ is separable. Say $cal(D)_j subset X_j$ is countable & dense. Then
  $ cal(B)_(X_j) = sigma ({ B^(X_j) (x_j , q) : x in cal(D)_j , q in bb(Q) > 0 }) , $
  where $B^(X_j) (x_j , q)$ is open metric #emph[Ball] in $X_j$ and $x$ is
  the center, $q$ is the radius.

  $ cal(B)_X = sigma ({product_(j = 1)^n B^(X_j) (x_j , q) : x_j in cal(D)_j , q in bb(Q) > 0}) , $
  so $cal(B)_X = times.circle.big_(j = 1)^n cal(B)_(X_j)$ .
]

#cor[
  $ cal(B)_(bb(R)^n) = times.circle.big_(j = 1)^n cal(B)_(bb(R)) . $
]

