#import "/book.typ": book-page
#import "../../../templates/conf.typ": *

#show: book-page.with()
#show: codly-init.with()
#show: thmrules.with(qed-symbol: $square$)

#counter(heading).update(5)
#set heading(numbering: "1.1.1")

// 上一节编号到 28
#counter(math.equation).update(28)

// 带有 label 的公式才编号
#set math.equation(numbering: "(1)", supplement: none, number-align: bottom)
#show math.equation.where(block: true): it => {
 if not it.has("label") {
   let fields = it.fields()
   fields.remove("body")
   fields.numbering = none
   return [#counter(math.equation).update(v => v - 1)#math.equation(..fields, it.body)<math-equation-without-label>]
 }
 return it
}

= The generalized power method
<the-generalized-power-method>
Let $upright(bold(A)) in bb(R)^(n times n)$ be an $n$ by $n$ real matrix. For simplicity, assume the eigenvalues of matrix $upright(bold(A))$ have different moduli.

The generalized power method reads: given a set of $n$ linearly independent vectors $upright(bold(x))_0^((j)) , j = 1 , 2 , dots.h.c$ and matrix $upright(bold(X))_0$ whose column vectors are ${upright(bold(x))_0^((j))}_(j = 1)^n$ , for $k = 0 , 1 , 2 , dots.h.c$ , do as follows

- Step 1. compute a new matrix $upright(bold(Z))_(k + 1)$ by

$ upright(bold(A)) upright(bold(X))_k arrow.r.double upright(bold(Z))_(k + 1) $

- Step 2. orthogonalize matrix $upright(bold(Z))_(k + 1)$ by the QR decomposition

  $ upright(bold(Z))_(k + 1) arrow.r.double upright(bold(X))_(k + 1) upright(bold(R))_(k + 1) $

  Here, matrix $upright(bold(X))_(k + 1)$ is an orthogonal matrix and matrix $upright(bold(R))_(k + 1)$ is a right triangular matrix. In the orthogonalization process, the first modulus-maximum entry for each column vector $upright(bold(x))_(k + 1)^((j))$ in matrix $upright(bold(X))_(k + 1)$ is fixed to have positive sign.

- Step 3. Check the difference of matrices $upright(bold(X))_k$ and $upright(bold(X))_(k + 1)$ . Stop the iteration if $norm(upright(bold(X))_(k + 1) - upright(bold(X))_k)$ is less than some pre-specified tolerance; otherwise, increase $k$ by one and go to Step 1.

The orthogonalization process in the generalized power method is critical. It guarantees that the column vectors in $upright(bold(X))_k$ are linearly independent. Once the sequence of matrices ${upright(bold(X))_k}$ converges, the column vectors will converge to linearly independent vectors, which may be (generalized) eigenvectors associated with different eigenvalues. Otherwise, if we normalize the column vectors individually and independently, all of the vectors may finally converge to a single common eigenvector. The normalization (more precisely ortho-normalization) of the column vectors of $upright(bold(Z))_(k + 1)$ can be done by either the Gram-Schmidt orthogonalization process or the Householder transformations.

Note that the first column vectors ${upright(bold(x))_k^((1))}_(k = 1)^oo$ are the same as those generated by the standard power method. This sequence must converge to the first eigenvector associated with the modulus-maximum eigenvalue. By the orthogonalization, the second column vectors ${upright(bold(x))_k^((2))}_(k = 1)^oo$ must converge to the second eigenvector associated with the second modulus-maximum eigenvalue. Similarly, the $j^(t h)$ column vectors ${upright(bold(x))_k^((j))}$ will converge to the $j^(t h)$ eigenvector associated with the $j^(t h)$ modulus-maximum eigenvalue, for $j = 3 , 4 , dots.h.c , n$ .

Assume the sequence of matrices ${upright(bold(X))_k}_(k = 1)^oo$ converges. For large $k$ , we have

$ upright(bold(X))_k approx upright(bold(X))_(k + 1) $

and

$ upright(bold(A)) upright(bold(X))_k approx upright(bold(X))_k upright(bold(R))_(k + 1) $

i.e.,

$ upright(bold(X))_k^(upright(T)) upright(bold(A)) upright(bold(X))_k approx upright(bold(R))_(k + 1) $<eq:29>

As the matrix on the left hand side of the identity above is similar to matrix $upright(bold(A))$ , the diagonal entries of the right triangular matrix are approximate eigenvalues of $upright(bold(A))$ . In the case that matrix $upright(bold(R))_(k + 1)$ is a diagonal matrix, the column vectors in $upright(bold(X))_k$ are approximate eigenvectors.

The initial matrix $upright(bold(X))_0$ for the generalized power iteration can be and even always is simply chosen to be the identity matrix, i.e., $upright(bold(X))_0 = upright(bold(I))$ . We may choose to terminate the iteration by checking whether the matrix $upright(bold(X))_k$ becomes fixed. We expect that for symmetric matrices or matrices that have $n$ real eigenvalues, the stopping criterion may work well.

However, for a general (non-symmetric) matrix that has complex eigenvalues, the generalized power method may fail to converge by the stopping criterion above since the identity (@eq:29) implies that all eigenvalues of $upright(bold(A))$ are real.

Let

$ upright(bold(A))_k = upright(bold(X))_k^(upright(T)) upright(bold(A)) upright(bold(X))_k $<eq:30>

Note that the matrix $upright(bold(A))_k$ has the same eigenvalues as $upright(bold(A))$ . We may stop the iteration when the structure of the matrix $upright(bold(A))_k$ is simple enough such that it is possible to directly compute all eigenvalues of $upright(bold(A))_k$ . For example, if the matrix $upright(bold(A))_k$ is a block right triangular matrix

$ upright(bold(A))_k = mat(delim: "[", upright(bold(R))_(1 , 1), upright(bold(R))_(1 , 2), upright(bold(R))_(1 , 3), dots.h.c, upright(bold(R))_(1 , s); #none, upright(bold(R))_(2 , 2), upright(bold(R))_(2 , 3), dots.h.c, upright(bold(R))_(2 , s); #none, , upright(bold(R))_(3 , 3), dots.h.c, upright(bold(R))_(3 , s); #none, , , dots.down, dots.v; #none, , , , upright(bold(R))_(3 , s)) $

with the diagonal matrices $upright(bold(R))_(i , i) (i = 1 , 2 , dots.h.c , s)$ be either $1 times 1$ or $2 times 2$ blocks, the eigenvalues of $upright(bold(A))_k$ can be easily computed.

#exr[
Write a $C \/ C + +$ computer program to find all eigenvalues of the following tridiagonal

matrix,

$ upright(bold(A)) = mat(delim: "[", 2, - 1, , , ; - 1, 2, - 1, , ; #none, dots.down, dots.down, dots.down, ; #none, , - 1, 2, - 1; #none, , , - 1, 2)_(n times n) , $

by the generalized power method. Print out the computed eigenvalues of $upright(bold(A))$ for $n = 6$ with six decimal digits.
]

#exr[
Write a $C \/ C + +$ computer program to find all eigenvalues of the following tridiagonal matrix,

$ upright(bold(A)) = mat(delim: "[", 2, 1, , , ; - 1, 2, 1, , ; #none, dots.down, dots.down, dots.down, ; #none, , - 1, 2, 1; #none, , , - 1, 2)_(n times n) , $

by the generalized power method. Print out the computed eigenvalues of $upright(bold(A))$ for $n = 6$ with six decimal digits. Note that this matrix has complex eigenvalues for $n > 1$ .
]

#rmk[
The generalized power method can be used to find a subset of the eigenvalues and the associated eigenvectors. In this case, the matrix $upright(bold(X))_k$ is a rectangular matrix in $bb(R)^(n times m)$ with $m < n$ and the right triangular matrix $upright(bold(R))_k$ is a square matrix in $bb(R)^(m times m)$ .
]

#exr[
Let $upright(bold(A)) in bb(R)^(n times n)$ be a real square matrix. Assume the matrix $upright(bold(A))$ has $n$ real eigenvalues $lambda_1 , lambda_2 , dots.h.c , lambda_n$ ; the eigenvalues have different moduli, satisfying

$ abs(lambda_1) > abs(lambda_2) > dots.h.c > abs(lambda_(n - 1)) > abs(lambda_n) > 0 . $

Denote by $upright(bold(v))_1 , upright(bold(v))_2 , dots.h.c , upright(bold(v))_n$ the eigenvectors associated with the eigenvalues $lambda_1 , lambda_2 , dots.h.c , lambda_n$ , respectively. We consider applying the generalized power method to simultaneously find all eigenvalues of the matrix A. Let

$ upright(bold(X))_0 = [upright(bold(x))_0^((1)) , upright(bold(x))_0^((2)) , dots.h.c , upright(bold(x))_0^((n - 1)) , upright(bold(x))_0^((n))] in bb(R)^(n times n) $

be the initial orthogonal matrix used for the generalized power iteration. Here, $upright(bold(x))_0^((j))$ is the $j^(upright("th "))$ column vector of $upright(bold(X))_0$ for $j = 1 , 2 , dots.h.c , n$ . Assume that

$ (upright(bold(x))_0^((j)) , upright(bold(v))_j) eq.not 0 quad "for" j = 1 , 2 , dots.h.c , n . $

Show that
1.  The similar matrix $upright(bold(A))_k = upright(bold(X))_k^T upright(bold(A)) upright(bold(X))_k$ in the generalized power method converges to a right triangular matrix $upright(bold(R))$ in the form

  $ upright(bold(R)) = mat(delim: "[", lambda_1, \*, \*, dots.h.c, \*; #none, lambda_2, \*, dots.h.c, \*; #none, , lambda_3, dots.h.c, \*; #none, , , dots.down, dots.v; #none, , , , lambda_n) , $

  where the eigenvalues ${lambda_i}_(i = 1)^n$ appear exactly in the decreasing order along the diagonal of $upright(bold(R))$ ; 

2. If the matrix $upright(bold(A))$ is symmetric, the similar matrix $upright(bold(A))_k$ converges to the diagonal matrix

$ upright(bold(Lambda)) = "diag" (lambda_1 , lambda_2 , dots.h.c , lambda_n) $
]

#rmk[
One disadvantage of the generalized power method is that the matrix-matrix multiplication and the QR decomposition involved in each iteration is generally very expensive (the computational work is proportional to $n^3$ ).
]

