#import "/book.typ": book-page
#import "../../../templates/conf.typ": *

#show: book-page.with()
#show: codly-init.with()
#show: thmrules.with(qed-symbol: $square$)

#counter(heading).update(7)
#set heading(numbering: "1.1.1")

// 上一节编号到 30
#counter(math.equation).update(30)

// 带有 label 的公式才编号
#set math.equation(numbering: "(1)", supplement: none, number-align: bottom)
#show math.equation.where(block: true): it => {
 if not it.has("label") {
   let fields = it.fields()
   fields.remove("body")
   fields.numbering = none
   return [#counter(math.equation).update(v => v - 1)#math.equation(..fields, it.body)<math-equation-without-label>]
 }
 return it
}

= The QR algorithm with shifts
<the-qr-algorithm-with-shifts>
Recall the shifted inverse power method can find a more accurate eigenvalue if an approximation to some eigenvalue is known. The method may even work more efficiently if the approximate eigenvalue is dynamically updated during the iteration, which we call the Rayleigh quotient accelerated inverse power method. The convergence rate of the method is cubic for symmetric matrices and quadratic for general non-symmetric matrices.

The QR algorithm can be similarly accelerated except we first need to introduce the inverse QR method or the generalized inverse power method and the method with shifting.

*Question*: what does the inverse QR method look like? At the first glance, one may imagine that the inverse QR method will look like the following one: given $upright(bold(B))_0 = upright(bold(X))_0^T upright(bold(A))^(- 1) upright(bold(X))_0$ with $upright(bold(X))_0$ be an orthogonal matrix, for $k = 0 , 1 , 2 , dots.h.c$ , do as follows

- Step 1. make QR decomposition for matrix $upright(bold(B))_k$

$ upright(bold(B))_k arrow.r.double upright(bold(Q))_(k + 1) upright(bold(R))_(k + 1) $

- Step 2. compute new matrix $upright(bold(B))_(k + 1)$ by

$ upright(bold(R))_(k + 1) upright(bold(Q))_(k + 1) arrow.r.double upright(bold(B))_(k + 1) $

Everything seems normal but the initial computation of matrix $upright(bold(B))_0$ will be too expensive since it involves direct computation of the inverse matrix $upright(bold(A))^(- 1)$ , which we usually need to avoid in scientific computing.

Fortunately, the QR method is itself the inverse QR method (or the genearalized power method is itself the generalized inverse method). There is no need to compute the inverse matrix $upright(bold(A))^(- 1)$ at all. To see the surprising fact, let us start with the generalized power method.

In this section, we will show that the generalized power method is itself the generalized inverse power method to some extent.

First recall that the orthogonalization of vectors can be made by either the QR decomposition or the PL decomposition, which factorizes a matrix as a product of an orthogonal matrix and a left/lower triangular matrix. The QR decomposition in the generalized power method can be replaced by the PL decomposition.

As the inverse transpose $upright(bold(A))^(- upright(T))$ has the same eigenvalues as matrix $upright(bold(A))^(- 1)$ , we apply the generalized power method to $upright(bold(A))^(- upright(T))$ and replace the QR decomposition by the PL decomposition. The generalized inverse power method now reads: given an initial orthogonal matrix $upright(bold(P))_0$ , for $k = 0 , 1 , 2 , dots.h.c$ , do as follows

- Step 1. compute new matrix $upright(bold(W))_(k + 1)$ by

$ upright(bold(A))^(- upright(T)) upright(bold(P))_k arrow.r.double upright(bold(W))_(k + 1) . $

- Step 2. orthogonalize matrix $upright(bold(W))_(k + 1)$ by the PL decomposition

  $ upright(bold(W))_(k + 1) arrow.r.double upright(bold(P))_(k + 1) upright(bold(L))_(k + 1) . $

  Here, matrix $upright(bold(P))_(k + 1)$ is an orthogonal matrix and matrix $upright(bold(L))_(k + 1)$ is a right triangular matrix. In the orthogonalization process, the first modulus-maximum entry for each column vector $upright(bold(p))_(k + 1)^((j))$ in matrix $upright(bold(P))_(k + 1) = (upright(bold(p))_(k + 1)^((1)) , upright(bold(p))_(k + 1)^((2)) , dots.h.c , upright(bold(p))_(k + 1)^((n)))$ is fixed to have positive sign.

- Step 3. Check the difference of matrices $upright(bold(P))_k$ and $upright(bold(P))_(k + 1)$ . Stop the iteration if $norm(upright(bold(P))_(k + 1) - upright(bold(P))_k)$ is less than some pre-specified tolerance; otherwise, increase $k$ by one and go to Step 1.

In the generalized inverse power method above, the last column vectors ${upright(bold(p))_k^((n))}_(k = 1)^oo$ are the same as those generated by the standard inverse power method. This sequence must converge to the eigenvector associated with the modulus-minimum eigenvalue of matrix A. By the orthogonalization, the column vectors ${upright(bold(p))_k^((n - 1))}$ must converge to the eigenvector associated with the second modulus-minimum eigenvalue of matrix $upright(bold(A))$ . Similarly, the $(n + 1 - j)^(t h)$ column vectors ${upright(bold(p))_k^((n + 1 - j))}$ will converge to the eigenvector associated with the $j^(upright("th "))$ modulus-minimum eigenvalue, for $j = 3 , 4 , dots.h.c , n$ .

When the modulus-minimum eigenvalue of $upright(bold(A))$ is much closer to zero in modulus than any other eigenvalues, the last column vectors ${upright(bold(p))_k^((n))}$ will converge to the eigenvector quickly.

Note that the matrices ${upright(bold(P))_k}$ by the generalized inverse power method satisfy the identity

$ upright(bold(A))^(- upright(T)) upright(bold(P))_k = upright(bold(P))_(k + 1) upright(bold(L))_(k + 1) $

or equivalently

$ upright(bold(A)) upright(bold(P))_k = upright(bold(P))_(k + 1) upright(bold(L))_(k + 1)^(- upright(T)) $<eq:31>

while the matrices ${upright(bold(X))_k}$ by the generalized power method satisfy

$ upright(bold(A)) upright(bold(X))_k = upright(bold(X))_(k + 1) upright(bold(R))_(k + 1) . $<eq:32>

Note that matrix $upright(bold(L))_(k + 1)^(upright(T))$ in (@eq:31) is a right triangular matrix. The right hand side of equation (@eq:31) is a QR decomposition of $upright(bold(A P))_k$ . The last two identities,(@eq:31)-(@eq:32), indicate that, if $upright(bold(P))_k = upright(bold(X))_k$ , then $upright(bold(P))_(k + 1) = upright(bold(X))_(k + 1)$ as well as $upright(bold(L))_(k + 1)^(- upright(T)) = upright(bold(R))_(k + 1)$ , by the uniqueness of the QR decomposition (provided that the signs of the diagonal entries of the triangular matrices $upright(bold(L))_(k + 1)$ and $upright(bold(R))_(k + 1)$ follow the same pattern). Thus, we conclude that the generalized inverse power method generates the same sequence of matrices ${upright(bold(X))_k}$ as the generalized power method if $upright(bold(P))_0 = upright(bold(X))_0$ . In this sense, the generalized power method itself can be regarded as the generalized inverse power method.

Notice that

$ mu_k^((n)) = (upright(bold(x))_k^((n)))^(upright(T)) upright(bold(A)) upright(bold(x))_k^((n)) $

approximates the entry at the lower-right corner of the right triangular matrix $upright(bold(R))_k$ . Vector $upright(bold(x))_k^((n))$ approximates the eigenvalue associated with the modulus-minimum eigenvalue of matrix $upright(bold(A))$ . The generalized shifted inverse power method now reads:

- Step 1. compute new matrix $upright(bold(W))_(k + 1)$ by

$ (upright(bold(A)) - mu_k^((n)) upright(bold(I)))^(- upright(T)) upright(bold(X))_k arrow.r.double upright(bold(W))_(k + 1) . $

- Step 2. orthogonalize matrix $upright(bold(W))_(k + 1)$ by the PL decomposition

$ upright(bold(W))_(k + 1) arrow.r.double upright(bold(X))_(k + 1) upright(bold(L))_(k + 1) . $

- Step 3. compute the approximate modulus-minimum eigenvalue

$ mu_(k + 1)^((n)) = (upright(bold(x))_(k + 1)^((n)))^(upright(T)) upright(bold(A)) upright(bold(x))_(k + 1)^((n)) . $

The generalized shifted power method that is equivalent to the one described above reads:

- Step 1. compute new matrix $upright(bold(Z))_(k + 1)$ by

$ (upright(bold(A)) - mu_k^((n)) upright(bold(I))) upright(bold(X))_k arrow.r.double upright(bold(Z))_(k + 1) . $

- Step 2. orthogonalize matrix $upright(bold(Z))_(k + 1)$ by the QR decomposition

$ upright(bold(Z))_(k + 1) arrow.r.double upright(bold(X))_(k + 1) upright(bold(R))_(k + 1) . $

- Step 3. compute the approximate modulus-minimum eigenvalue

$ mu_(k + 1)^((n)) = (upright(bold(x))_(k + 1)^((n)))^(upright(T)) upright(bold(A)) upright(bold(x))_(k + 1)^((n)) . $

Now the shifted QR method reads: given an initial orthogonal matrix $upright(bold(X))_0$ and matrix $upright(bold(A))_0 = upright(bold(X))_0^T upright(bold(A)) upright(bold(X))_0$ , for $k = 0 , 1 , 2 , dots.h.c$ , do as follows

- Step 1. make QR decomposition for the shifted matrix $(upright(bold(A))_k - mu_k^((n)) upright(bold(I)))$

$ upright(bold(A))_k - mu_k^((n)) upright(bold(I)) arrow.r.double upright(bold(Q))_(k + 1) upright(bold(R))_(k + 1) . $

- Step 2. compute new matrix $upright(bold(A))_(k + 1)$ by

$ upright(bold(R))_(k + 1) upright(bold(Q))_(k + 1) + mu_k^((n)) upright(bold(I)) arrow.r.double upright(bold(A))_(k + 1) . $

- Step 3. compute the approximate modulus-minimum eigenvalue

  $ mu_(k + 1)^((n)) = (upright(bold(x))_(k + 1)^((n)))^T upright(bold(A)) upright(bold(x))_(k + 1)^((n)) $

  which is the entry at the lower-right corner of matrix $upright(bold(A))_(k + 1)$ (so there are no any real arithmetic operations needed in this step).

We remark that the shift $mu_(k + 1)^((n))$ can be chosen differently. Let

$ mat(delim: "(", a_(n - 1 , n - 1), a_(n - 1 , n); a_(n , n - 1), a_(n , n)) $

be the two by two matrix at the lower-right corner of matrix $upright(bold(A))_(k + 1)$ . Among those two eigenvalues of the matrix, we may choose $mu_(k + 1)^((n))$ to be the one which is closer to $a_(n , n)$ if both eigenvalues are real; choose each of them once in two consecutive iterations if the eigenvalues are complex. The latter case corresponds to the QR method with double shifts.