#import "/book.typ": book-page
#import "../../../templates/conf.typ": *

#show: book-page.with()
#show: codly-init.with()
#show: thmrules.with(qed-symbol: $square$)

#counter(heading).update(2)
#set heading(numbering: "1.1.1")

// 上一节编号到 16
#counter(math.equation).update(16)

// 带有 label 的公式才编号
#set math.equation(numbering: "(1)", supplement: none, number-align: bottom)
#show math.equation.where(block: true): it => {
 if not it.has("label") {
   let fields = it.fields()
   fields.remove("body")
   fields.numbering = none
   return [#counter(math.equation).update(v => v - 1)#math.equation(..fields, it.body)<math-equation-without-label>]
 }
 return it
}

= The inverse power method
<the-inverse-power-method>
In this and the next section, we also assume matrix $upright(bold(A))$ is symmetric and the set of eigenvectors ${upright(bold(v))_j}_(j = 1)^n$ forms an orthonormal basis of $bb(R)^n$ even though the methods introduced will be applicable to non-symmetric matrices as the original power method except that in this case we will not be able to observe the quadratic converge rate (with respect to the ratio of the first two modulus-maximum eigenvalues) for the approximate eigenvalues.

This section will show us that the power method can be used to find not only the modulus-maximum eigenvalue but also the modulus-minimum eigenvalue. Assume that

$ abs(lambda_1) gt.eq abs(lambda_2) gt.eq dots.h.c gt.eq abs(lambda_(n - 1)) > abs(lambda_n) > 0 . $

That is, the modulus of the last eigenvalue is strictly less than others.

Note that symmetric matrix $upright(bold(A))$ has the same set of eigenvectors as its inverse $upright(bold(A))^(- 1)$ and the modulus-minimum eigenvalue of $upright(bold(A))$ is the reciprocal of the modulus-maximum eigenvalue of the inverse matrix $upright(bold(A))^(- 1)$ . So we can apply the power method to the inverse matrix for the modulus-minimum eigenvalue. The corresponding power method working with the inverse matrix is called the inverse power method. It takes the following form, for $k = 0 , 1 , 2 , dots.h.c$ ,

- Step 1. solve the linear system: $upright(bold(A)) upright(bold(z))_(k + 1) = upright(bold(x))_k$ ;

- Step 2. normalize vector $upright(bold(z))_(k + 1)$ : choose $r_(k + 1)$ such that the 2-norm of vector

  $ upright(bold(x))_(k + 1) = 1 / r_(k + 1) upright(bold(z))_(k + 1) $

  is equal to one and its first modulus-maximum entry has positive sign. If $norm(upright(bold(x))_(k + 1) - upright(bold(x))_k)_oo$ is less than a specified tolerance, compute

  $ mu_(k + 1) = upright(bold(x))_(k + 1)^T upright(bold(A)) upright(bold(x))_(k + 1) $

  and stop the iteration; otherwise, increase $k$ by one and go to step 1 .

Note that the inverse power method needs to solve a linear system in each iteration.

As the power method, the sequence of vectors ${upright(bold(x))_k}_(k = 1)^oo$ generated by the inverse power method converges linearly to the eigenvector associated with the modulus-minimum eigenvalue of matrix A. Similar to estimates (14) and (16), it can be shown that, for large $k$ ,

$ mu_(k + 1) - lambda_n approx (mu_k - lambda_n) (lambda_n / lambda_(n - 1))^2 . $<eq:17>

and

$ abs(mu_k - lambda_n) lt.eq C norm(upright(bold(x))_k - upright(bold(v))_n)^2 $<eq:18>

with some positive generic constant $C > 0$ .

With respect to the convergence of the approximate eigenvectors, we also have results similar to the estimates (6)-(7). We have, for large $k$ ,

$ norm(upright(bold(x))_k - upright(bold(v))_n)_2 lt.eq C (abs(lambda_n) / abs(lambda_(n - 1)))^k . $<eq:19>

If $abs(lambda_(n - 2)) > abs(lambda_(n - 1))$ , we have the approximation

$ upright(bold(x))_(k + 1) - upright(bold(v))_n approx lambda_n / lambda_(n - 1) (upright(bold(x))_k - upright(bold(v))_n) $<eq:20>

for large $k$ . This indicates that the sequence of eigenvectors has linear convergence.

#exr[
Let

$ upright(bold(A))_n = mat(delim: "[", 2, - 1, , , ; - 1, 2, - 1, , ; #none, dots.down, dots.down, dots.down, ; #none, , - 1, 2, - 1; #none, , , - 1, 2)_(n times n) . $

Write a computer program to find the modulus-minimum eigenvalue of the matrxi $upright(bold(A))_n$ with the inverse power method.
]

#exr[
Let

$ upright(bold(A))_n = 1 / (n + 1)^3 mat(delim: "[", n, n - 1, n - 2, dots.h.c, 2, 1; n - 1, 2 (n - 1), 2 (n - 2), dots.h.c, 4, 2; n - 2, 2 (n - 2), 3 (n - 2), dots.down, 6, 3; dots.v, dots.v, dots.down, dots.down, dots.v, dots.v; 2, 4, 6, dots.h.c, 2 (n - 1), n - 1; 1, 2, 3, dots.h.c, n - 1, n)_(n times n) . $

Write a computer program to find the modulus-minimum eigenvalue of the matrxi $upright(bold(A))_n$ with the inverse power method.
]

