#import "../book.typ": *

#show: book-page.with(
  title: "1.4 Construction of Measures"
)

== Construction of Measures

In measure theory, a primary objective is to define a measure on a #strong[$sigma$-algebra];, which is a collection of sets that is robust enough for defining integrals and probabilities. However, it is often easier to first define a more basic function, a #strong[premeasure];, on a simpler structure called an #strong[algebra] of sets. This interion outlines the standard procedure, known as the #strong[Carathéodory extension theorem];, for extending a premeasure on an algebra to a full measure on the $sigma$-algebra generated by that algebra.



=== Premeasures and Outer Measures

We begin by defining the initial objects of our construction.

#definition(title: "Premeasures")[
Let $X$ be a non-empty set. A function $mu_0 : cal(A) arrow.r [0, +oo]$ is called a #strong[premeasure] on the algebra $cal(A)$ if it satisfies the following conditions:

  + #strong[Null Empty Set:] $mu_0 (nothing) = 0$.
  + #strong[Countable Additivity:] If ${ A_j }_(j = 1)^oo$ is a sequence of #strong[disjoint] sets in $cal(A)$ such that their union $union.big_(j = 1)^oo A_j$ is also in $cal(A)$, then: $ mu_0 (union.big_(j = 1)^oo A_j) = sum_(j = 1)^oo mu_0 (A_j). $
]


Our goal is to extend the premeasure $mu_0$ from the algebra $cal(A)$ to a measure on $sigma (cal(A))$, the smallest $sigma$-algebra containing $cal(A)$. The first step in this process is to define an #strong[outer measure] that is defined for #emph[all] subsets of $X$.

#definition(title: "Outer Measure")[
An #strong[outer measure] on $X$ is a function $mu^* : cal(P) (X) arrow.r [0, +oo]$ that satisfies:

1. #strong[Null Empty Set:] $mu^* (nothing) = 0$.
2. #strong[Monotonicity:] If $A subset.eq B subset.eq X$, then $mu^* (A) lt.eq mu^* (B)$.
3. #strong[Countable Subadditivity:] For any sequence of sets ${ A_j }_(j = 1)^oo subset.eq cal(P) (X)$ (not necessarily disjoint), $ mu^* (union.big_(j = 1)^oo A_j) lt.eq sum_(j = 1)^oo mu^* (A_j). $
]

An outer measure provides a way to assign a "size" to every subset of $X$, although it lacks the full additivity property required of a true measure.

#proposition[
Let $(X , cal(A) , mu_0)$ be a premeasure space. The function $mu^* : cal(P) (X) arrow.r [0, +oo]$ defined for any $E subset.eq X$ by $ mu^* (E) := inf {sum_(j = 1)^oo mu_0 (A_j) : { A_j }_(j = 1)^oo subset.eq cal(A) "and" E subset.eq union.big_(j = 1)^oo A_j} $ is an outer measure on $X$.
]

This definition effectively approximates the "size" of an arbitrary set $E$ from the outside by finding the smallest possible total measure of a countable collection of sets from the algebra $cal(A)$ that covers $E$.

=== Carathéodory's Criterion and Measurable Sets

The outer measure $mu^*$ is defined on all subsets of $X$, but it is generally not countably additive on $cal(P) (X)$. The next crucial step, due to Carathéodory, is to identify a subcollection of $cal(P) (X)$ on which $mu^*$ #emph[does] behave like a measure.

#definition(title: [$mu^*$-Measurable Sets])[
Let $mu^*$ be an outer measure on $X$. A set $A subset.eq X$ is said to be #strong[$mu^*$-measurable] if it satisfies the #strong[Carathéodory condition];: for every set $E subset.eq X$, $ mu^* (E) = mu^* (E inter A) + mu^* (E inter A^complement) $ where $A^complement = X \\ A$.
]

#note-box[
Since outer measures are subadditive, the inequality $mu^* (E) lt.eq mu^* (E inter A) + mu^* (E inter A^complement)$ is always true. Therefore, to prove a set $A$ is $mu^*$-measurable, one only needs to show the reverse inequality: $mu^* (E) gt.eq mu^* (E inter A) + mu^* (E inter A^complement)$ for all $E subset.eq X$. The condition essentially requires that the set $A$ "splits" any other set $E$ in an additive way.
]


The collection of all $mu^*$-measurable sets forms the domain on which we can define our final measure.

#theorem(title: "Carathéodory's Theorem")[
Let $mu^*$ be an outer measure on $X$. The collection $cal(M)$ of all $mu^*$-measurable sets,
$ cal(M) := { A subset.eq X : mu^* (E) = mu^* (E inter A) + mu^* (E inter A^complement) "for all" E subset.eq X } $
is a #strong[$sigma$-algebra];, and the restriction of $mu^*$ to $cal(M)$, denoted $mu = mu^* \|_(cal(M))$, is a #strong[complete measure];.
]


=== The Carathéodory Extension Theorem

The final theorem connects all the preceding concepts to achieve our initial goal: extending the premeasure $mu_0$ on $cal(A)$ to a measure $mu$ on $sigma (cal(A))$.

#theorem(title: "Carathéodory Extension Theorem")[
Let $mu_0$ be a premeasure on an algebra $cal(A) subset.eq cal(P) (X)$, and let $mu^*$ be the outer measure induced by $mu_0$. Then:

+ #strong[Existence:] The $sigma$-algebra $sigma (cal(A))$ generated by $cal(A)$ is contained within the $sigma$-algebra $cal(M)$ of $mu^*$-measurable sets. The restriction of $mu^*$ to $sigma (cal(A))$, denoted by $mu = mu^* \|_(sigma (cal(A)))$, is a measure that extends $mu_0$ (i.e., $mu (A) = mu_0 (A)$ for all $A in cal(A)$).

+ #strong[Uniqueness:] If another measure $nu$ on $sigma (cal(A))$ also extends $mu_0$, then $nu (E) lt.eq mu (E)$ for all $E in sigma (cal(A))$. Equality holds if $mu (E) < oo$.

+ #strong[Uniqueness for $sigma$-finite Premeasures:] If the premeasure $mu_0$ is #strong[$sigma$-finite], then the extension $mu$ is the #strong[unique] measure on $sigma (cal(A))$ that extends $mu_0$.
]

This powerful theorem forms the foundation for constructing many important measures in mathematics, including the Lebesgue measure on the real line.