#import "../book.typ": *

#show: book-page.with(
  title: "1.5 One-Dimensional Lebesgue-Stieltjes Measures"
)

== One-Dimensional Lebesgue-Stieltjes Measures

This interion introduces the construction of Lebesgue-Stieltjes measures on the real line, $bb(R)$. These measures generalize the concept of length to more complex sets and are fundamental to modern analysis.

=== Construction of the Measure

The construction begins by defining a measure on a simple collection of sets and then extending it to a much larger class, the Borel sets, and beyond.

The foundational sets for our construction are #strong[h-intervals];, which are sets of the form $(a , b]$ for $- oo lt.eq a < b lt.eq + oo$. We also include the empty set, $nothing$.

Let $cal(A)$ be the collection of all finite disjoint unions of h-intervals. This collection forms an #strong[algebra] of sets, meaning it is closed under finite unions and complementation.

Let $F : bb(R) arrow.r bb(R)$ be a monotonically increasing and right-continuous function. We can define a set function $mu_0$ on the algebra $cal(A)$ as follows:
$
mu_0 (A ) = cases(delim: "{",
  0 & "if" A = nothing,
  sum_(j = 1)^n (F (b_j ) - F (a_j)) & "if" A = union.sq.big_(j = 1)^n ( a_j , b_j]).
$
This function $mu_0$ can be shown to be a #strong[premeasure] on the algebra $cal(A)$.

The #strong[Carathéodory Extension Theorem] provides a standard way to extend a premeasure on an algebra to a complete measure on a $sigma$-algebra.
Applying this theorem to $mu_0$ on $cal(A)$, we obtain a complete measure $mu_F$ defined on a $sigma$-algebra $cal(M)_F$. This $sigma$-algebra $cal(M)_F$ contains the #strong[Borel $sigma$-algebra];, $cal(B) (bb(R) )$, which is the smallest $sigma$-algebra containing all open sets in $bb(R)$ (and is also generated by the algebra $cal(A)$, i.e., $sigma (cal(A)) = cal(B) ( bb(R))$).

The measure $mu_F$ is called the #strong[Lebesgue-Stieltjes measure] associated with the function $F$.

An important property concerning uniqueness is that two such measures are identical if and only if their generating functions differ by a constant.

#proposition[
For two increasing, right-continuous functions $F$ and $G$, we have $mu_F = mu_G$ if and only if $F (x ) = G ( x) + c$ for some constant $c$.
]

=== Regularity Properties

Lebesgue-Stieltjes measures possess important topological properties known as regularity. For this discussion, let $mu$ be a complete Lebesgue-Stieltjes measure on $bb(R)$ with domain $cal(M)_mu$.

The measure of any set $E in cal(M)_mu$ can be determined by approximating it with countable covers of h-intervals: $ mu (E ) = inf {sum_(j = 1)^oo mu (( a_j , b_j]) : E subset.eq union.big_(j = 1)^oo (a_j , b_j]}. $ A key lemma shows that we can equivalently use open intervals for these covers.

#lemma[
For any set $E in cal(M)_mu$, $ mu (E ) = inf {sum_(j = 1)^oo mu ((a_j , b_j)) : E subset.eq union.big_(j = 1)^oo ( a_j , b_j)}. $
]

#proof[
Let's denote the proposed equivalent definition using open intervals by $nu (E)$. We need to prove that $mu (E) = nu (E)$.

1. #strong[Proving $mu (E) gt.eq nu (E)$:]

  By the definition of $mu (E)$, for any $epsilon > 0$, there exists a countable cover of $E$ by half-open intervals ${ (a_j , b_j ] }_(j = 1)^oo$ such that:
  $ sum_(j = 1)^oo mu (( a_j , b_j]) < mu (E) + epsilon / 2. $
  Since the generating function $F$ is right-continuous, for each $j$, there exists a $delta_j > 0$ such that:
  $ F (b_j + delta_j) - F (b_j) < epsilon / 2^(j + 1). $
  This implies that $mu ((b_j , b_j + delta_j]) < epsilon / 2^(j + 1)$.

  Now, consider the collection of open intervals ${ (a_j , b_j + delta_j) }_(j = 1)^oo$. Since $(a_j , b_j ] subset (a_j , b_j + delta_j)$, this collection forms an open cover for $E$. By the definition of $nu (E)$, we have:
  $ nu (E) lt.eq sum_(j = 1)^oo mu ((a_j , b_j + delta_j)). $
  Since our measure $mu$ is generated from $F$, we can write:
  $ mu ((a_j , b_j + delta_j)) lt.eq mu ((a_j , b_j + delta_j]) = mu ((a_j , b_j]) + mu ((b_j , b_j + delta_j]). $
  Summing over all $j$, we get:
  $
  sum_(j = 1)^oo mu ((a_j , b_j + delta_j)) &lt.eq sum_(j = 1)^oo mu (( a_j , b_j]) + sum_(j = 1)^oo mu ((b_j , b_j + delta_j]) \
  &< (mu (E) + epsilon / 2) + sum_(j = 1)^oo epsilon / 2^(j + 1) \
  &= mu (E) + epsilon.
  $
  Therefore, $nu (E) < mu (E) + epsilon$. As this holds for any $epsilon > 0$, we conclude that $nu (E) lt.eq mu (E)$.

2. #strong[Proving $mu (E) lt.eq nu (E)$:]

  Let ${ (a_j , b_j) }_(j = 1)^oo$ be any countable open cover of $E$. The union $O = union.big_(j = 1)^oo (a_j , b_j)$ is an open set, and therefore a measurable set in $cal(M)_mu$. By the monotonicity of the measure $mu$, since $E subset.eq O$, we have $mu (E) lt.eq mu (O)$. Furthermore, by the countable subadditivity of $mu$:
  $ mu (O) = mu (union.big_(j = 1)^oo (a_j , b_j)) lt.eq sum_(j = 1)^oo mu ((a_j , b_j)). $
  Combining these inequalities gives:
  $ mu (E) lt.eq sum_(j = 1)^oo mu ((a_j , b_j)). $
  This inequality holds for #emph[any] countable open cover of $E$. Taking the infimum over all such covers, we obtain:
  $ mu (E) lt.eq inf {sum_(j = 1)^oo mu ((a_j , b_j)) : E subset.eq union.big_(j = 1)^oo (a_j , b_j)} = nu (E). $
  Combining the results from Part 1 and Part 2, we have $mu (E) = nu (E)$.
]

This lemma is a crucial step in proving the general regularity theorem.

#theorem[
Let $mu$ be a Lebesgue-Stieltjes measure and $E in cal(M)_mu$. Then:
1. #strong[Outer Regularity:]; $mu (E ) = inf { mu (O ) : O "is open," E subset.eq O }$.
2. #strong[Inner Regularity:]; $mu ( E) = sup { mu ( K) : K upright("is compact,") K subset.eq E }$.
]

#proof[
1. #strong[Outer Regularity:]

  From the lemma, we know that for any $epsilon > 0$, there exists a countable collection of open intervals ${ (a_j , b_j) }_(j = 1)^oo$ that covers $E$ and satisfies:
  $ sum_(j = 1)^oo mu ((a_j , b_j)) < mu (E) + epsilon. $
  Let $O = union.big_(j = 1)^oo (a_j , b_j)$. By construction, $O$ is an open set and $E subset.eq O$. By the countable subadditivity of $mu$: $ mu (O) = mu (union.big_(j = 1)^oo (a_j , b_j)) lt.eq sum_(j = 1)^oo mu ((a_j , b_j)) < mu (E) + epsilon. $ Thus, for any $epsilon > 0$, we have found an open set $O supset.eq E$ with $mu (O) < mu (E) + epsilon$. This directly implies that $mu (E) = inf { mu (O) : O "is open and" E subset.eq O }$.

2. #strong[Inner Regularity:]

]

This theorem states that any measurable set can be approximated "from the outside" by open sets and "from the inside" by compact sets.



=== Structure of Measurable Sets

The regularity property provides deep insight into the structure of measurable sets. They are, in a sense, "close" to being topologically simpler sets like open or closed sets.

#definition[
- A #strong[$G_delta$ set] is a set that can be written as a countable interinterion of open sets.
- An #strong[$F_sigma$ set] is a set that can be written as a countable union of closed sets.
]

Note that all $G_delta$ and $F_sigma$ sets are Borel sets.

A fundamental theorem characterizes all Lebesgue-Stieltjes measurable sets in terms of these Borel sets.

#theorem[
Let $E subset.eq bb(R)$. The following are equivalent:
1. $E$ is $mu$-measurable (i.e., $E in cal(M)_mu$).
2. $E = V \\ N_1$, where $V$ is a $G_delta$ set and $mu (N_1 ) = 0$.
3. $E = H union N_2$, where $H$ is an $F_sigma$ set and $mu ( N_2) = 0$.
]

#proof[
- #strong[2, 3 $arrow.r.double$ 1:] This follows from the completeness of the measure $mu$. Since $V$ and $H$ are Borel sets, they are in $cal(M)_mu$. Any subset of a null set (like $N_1$ or $N_2$) is also in $cal(M)_mu$. The collection $cal(M)_mu$ is a $sigma$-algebra, so it is closed under set difference and union, implying $E in cal(M)_mu$.

- #strong[1 $arrow.r.double$ 2, 3:] Assume $E in cal(M)_mu$. By regularity, for each integer $j gt.eq 1$, we can find an open set $O_j supset.eq E$ and a closed set $C_j subset.eq E$ such that $mu (O_j \\ E ) < 1 \/ j$ and $mu ( E \\ C_j) < 1 \/ j$. (This requires handling the case of infinite measure by decomposing $E$).
  - Let $V = inter.big_(j = 1)^oo O_j$. Then $V$ is a $G_delta$ set, $E subset.eq V$, and one can show $mu (V \\ E ) = 0$. Thus $E = V \\ ( V \\ E)$, which is form (2).
  - Let $H = union.big_(j = 1)^oo C_j$. Then $H$ is an $F_sigma$ set, $H subset.eq E$, and one can show $mu (E \\ H ) = 0$. Thus $E = H union ( E \\ H)$, which is form (3).
]

This result is often summarized by #strong[Littlewood's First Principle of Measure Theory];: Every measurable set is "nearly" an open set (or a closed set).


=== The Lebesgue Measure on $bb(R)$

A canonical example is the #strong[Lebesgue measure] on $bb(R)$, denoted by $m$ or $cal(L)^1$. It is the Lebesgue-Stieltjes measure generated by the identity function $F (x) = x$.

For an interval $I$, its Lebesgue measure $m (I)$ is simply its length. Its domain, $cal(M)_m$, is the collection of #strong[Lebesgue measurable sets];.

The theory of Lebesgue measure reveals a distinction between the topological size (e.g., dense, uncountable) and the measure-theoretic size of a set.

==== Open Dense Sets with Arbitrarily Small Measure
A set can be topologically "large" (dense) but measure-theoretically "small".

#example[
Let ${ q_j }_(j = 1)^oo$ be an enumeration of the rational numbers in $(0 , 1 )$. For any $epsilon > 0$, define the open set: $ O_epsilon = union.big_(j = 1)^oo (q_j - epsilon / 2^(j + 1) , q_j + epsilon / 2^(j + 1)). $ This set is open and dense in $(0 , 1)$ because it contains all the rationals. However, its measure is small: $ m ( O_epsilon) lt.eq sum_(j = 1)^oo m ((q_j - epsilon / 2^(j + 1) , q_j + epsilon / 2^(j + 1))) = sum_(j = 1)^oo epsilon / 2^j = epsilon. $
]

==== The Cantor Set: An Uncountable Null Set
A set can have measure zero but be uncountably infinite.

#example[
The standard ternary #strong[Cantor set] $C$ is constructed by iteratively removing the open middle third of intervals, starting from $[0 , 1]$.
- The total length removed is
  $
  sum_(j = 0)^oo 2^j / 3^(j + 1) = 1 / 3 sum_(j = 0)^oo (2 / 3 )^j = 1 / 3 frac(1, 1 - 2 \/ 3) = 1.
  $
  Therefore, the measure of the remaining set is $m (C ) = m ([0 , 1] ) - 1 = 0$. However, one can establish a bijection between $C$ and $[0 , 1]$, proving that $C$ is uncountable.
- The #strong[Cantor-Lebesgue function] (or "Devil's Staircase") is a function $phi.alt : [0 , 1] arrow.r [0 , 1]$ that is continuous, non-decreasing, with $phi.alt (0 ) = 0$ and $phi.alt (1 ) = 1$. Its derivative $phi.alt' (x)$ is zero on the complement of the Cantor set. Since $m ( C) = 0$, $phi.alt' ( x) = 0$ almost everywhere. This demonstrates a failure of the classical Fundamental Theorem of Calculus for this function:
  $
  integral_0^1 phi.alt' ( x) thin d x = 0 eq.not 1 = phi.alt ( 1) - phi.alt ( 0).
  $
]

==== Existence of Non-Borel Lebesgue Measurable Sets

The collection of Lebesgue measurable sets is strictly larger than the Borel sets: $cal(B) (bb(R) ) subset.neq cal(M)_m$.

#proof[
The cardinality of the Borel sets $cal(B) (bb(R))$ is equal to the cardinality of the continuum, $abs(bb(R)) = frak(c)$. However, the Cantor set $C$ has measure 0. Since the Lebesgue measure is complete, every subset of $C$ is Lebesgue measurable. The power set of $C$, $cal(P) ( C)$, has cardinality $2^(frak(c)) > frak(c)$. Thus, there are more Lebesgue measurable sets than Borel sets.
]

==== Existence of Non-Lebesgue Measurable Sets

Not all subsets of $bb(R)$ are Lebesgue measurable. The construction of such a set, known as a #strong[Vitali set];, requires the Axiom of Choice.

#strong[Construction:] Define an equivalence relation on $bb(R)$ by $x tilde.op y$ if and only if $x - y in bb(Q)$. Let $V$ be a set containing exactly one representative from each equivalence class in $[0 , 1 )$.

#proof[
Assume, for contradiction, that $V$ is Lebesgue measurable. Let ${ q_k }_(k = 1)^oo$ be an enumeration of $bb(Q) inter [ - 1 , 1]$. Consider the sets $V_k = V + q_k = { v + q_k : v in V }$.

1. The sets $V_k$ are disjoint translates of $V$. By the translation-invariance of the Lebesgue measure, $m (V_k ) = m (V )$ for all $k$.
2. The union $union.big_(k = 1)^oo V_k$ covers the interval $[ 0 , 1 )$.
3. If $m (V ) = 0$, then by countable additivity, $m (union.big V_k) = sum m (V_k ) = 0$. This contradicts the fact that the union covers $[ 0 , 1)$, which has measure $1$.
4. If $m ( V) > 0$, then $sum_(k = 1)^oo m ( V_k) = oo$. However, the entire union is contained within $[ - 1 , 2)$, which has a finite measure of $3$. This is also a contradiction. Since both cases lead to a contradiction, the set $V$ cannot be Lebesgue measurable.
]
