#import "../book.typ": *

#show: book-page.with(
  title: "1.2 Sigma Algebra"
)

== $sigma$-algebra

=== $sigma$-Algebras

In measure theory, we need a way to define which subsets of a given set are "measurable." This collection of measurable subsets should be stable under standard set operations. This leads to the concept of a $sigma$-algebra.

#definition[
Let $X$ be a non-empty set. A collection of subsets of $X$, denoted by $cal(A) subset.eq cal(P) (X)$, is defined as follows:

+ $cal(A)$ is an #strong[algebra] if it satisfies the following three properties:

  - The entire set $X$ is in $cal(A)$ (i.e., $X in cal(A)$).
  - $cal(A)$ is closed under complementation: If $E in cal(A)$, then its complement $E^complement = X \\ E$ is also in $cal(A)$.
  - $cal(A)$ is closed under finite unions: If $E_1 , E_2 , dots.h , E_n in cal(A)$, then their union $union.big_(j = 1)^n E_j$ is also in $cal(A)$.

+ An algebra $cal(A)$ is a #strong[$sigma$-algebra] if it is closed under #emph[countable] unions. That is, if ${ E_k }_(k = 1)^oo subset.eq cal(A)$, then $union.big_(k = 1)^oo E_k in cal(A)$.
]

#remark[
In the definition of a $sigma$-algebra, "countable unions" can be replaced by "disjoint countable unions." Any countable union of sets can be represented as a countable disjoint union. Specifically, given a sequence of sets ${ E_k }_(k = 1)^oo$, we can define a sequence of pairwise disjoint sets ${ tilde(E)_k }_(k = 1)^oo$ with the same union:
$ union.big_(k = 1)^oo E_k = union.big.sq_(k = 1)^oo tilde(E)_k. $
where $union.big.sq$ denotes a disjoint union, and the sets $tilde(E)_k$ are defined as: $ tilde(E)_1 = E_1 , quad "and for" n > 1 , quad tilde(E)_n = E_n \\ (union.big_(j = 1)^(n - 1) E_j). $
]

#example[
+ #strong[Trivial and Power Set $sigma$-Algebras:] For any non-empty set $X$, the collections ${ nothing , X }$ and the power set $cal(P) (X)$ are both $sigma$-algebras. The former is the smallest possible $sigma$-algebra, and the latter is the largest.

+ #strong[Countable-Cocountable $sigma$-Algebra:] If $X$ is an uncountable set, the collection $ cal(F) := { E subset.eq X mid(|) E "is countable or" E^complement "is countable" } $ is a $sigma$-algebra. To verify this, consider a countable collection of sets ${ E_j }_(j = 1)^oo subset.eq cal(F)$.

  - If all $E_j$ are countable, their union $union.big_(j = 1)^oo E_j$ is also countable and thus is in $cal(F)$.
  - If at least one set, say $E_(j_0)$, has a countable complement (i.e., is co-countable), then the complement of the union satisfies $(union.big_(j = 1)^oo E_j)^complement = inter.big_(j = 1)^oo E_j^complement subset.eq E_(j_0)^complement$. Since $E_(j_0)^complement$ is countable, any subset of it is also countable. Therefore, $(union.big_(j = 1)^oo E_j)^complement$ is countable, which means $union.big_(j = 1)^oo E_j in cal(F)$.

+ #strong[Interinterion of $sigma$-Algebras:] Let ${ cal(F)_i }_(i in I)$ be a collection of $sigma$-algebras on $X$, where $I$ is an arbitrary indexing set. Then their interinterion, $inter.big_(i in I) cal(F)_i$, is also a $sigma$-algebra on $X$. This property is crucial as it guarantees the existence of a minimal $sigma$-algebra containing a given collection of subsets.
]


=== Generated $sigma$-Algebras

Often, we want to find the smallest $sigma$-algebra that contains a specific collection of subsets.

#definition[
Let $cal(E) subset.eq cal(P) (X)$ be an arbitrary collection of subsets of $X$. The #strong[$sigma$-algebra generated by $cal(E)$];, denoted $sigma (cal(E))$, is defined as the interinterion of all $sigma$-algebras on $X$ that contain $cal(E)$:

$ sigma (cal(E)) := inter.big { cal(F) mid(|) cal(F) "is a" sigma "-algebra on" X "and" cal(E) subset.eq cal(F) }. $

This interinterion is indeed a $sigma$-algebra. It is the smallest (or coarsest) $sigma$-algebra containing $cal(E)$.
]

#proposition[
Let $cal(E)_1 subset.eq cal(P) (X)$ be an arbitrary collection of subsets and let $cal(E)_2 subset.eq sigma (cal(E)_1)$. Then $sigma (cal(E)_2) subset.eq sigma (cal(E)_1)$.
]

#proof[
Since $sigma (cal(E)_1)$ is a $sigma$-algebra and it contains $cal(E)_2$, by the definition of the generated $sigma$-algebra, it must also contain the smallest $sigma$-algebra containing $cal(E)_2$, which is $sigma (cal(E)_2)$. Thus, $sigma (cal(E)_2) subset.eq sigma (cal(E)_1)$.
]

=== Borel $sigma$-Algebras

A particularly important type of $sigma$-algebra is generated by the open sets of a topological space.

#definition[
Let $(X , tau)$ be a topological space, where $tau$ is the collection of open sets in $X$. The #strong[Borel $sigma$-algebra] on $X$, denoted $cal(B)_X$, is the $sigma$-algebra generated by the collection of open sets $tau$: $ cal(B)_X := sigma (tau) $ The elements of $cal(B)_X$ are called #strong[Borel sets];.
]

#proposition[
On the real line $bb(R)$ equipped with its standard (Euclidean) topology, the Borel $sigma$-algebra $cal(B)_(bb(R))$ can be generated by various collections of intervals. The following collections all generate $cal(B)_(bb(R))$: $ cal(B)_(bb(R)) = sigma (cal(A)_i) quad "for any " i in { 1 , dots.h , 5 }. $
where:
1. Open intervals: $cal(A)_1 = { (a , b) : a , b in bb(R) , a < b }$.
2. Closed intervals: $cal(A)_2 = { \[ a , b \] : a , b in bb(R) , a < b }$.
3. Half-open intervals: $cal(A)_3 = { (a , b \] : a , b in bb(R) , a < b }$ or ${ \[ a , b) : a , b in bb(R) , a < b }$.
4. Open rays: $cal(A)_4 = { (a , + oo) : a in bb(R) }$ or ${ (- oo , a) : a in bb(R) }$.
5. Closed rays: $cal(A)_5 = { \[ a , + oo \) : a in bb(R) }$ or ${ \( - oo , a \] : a in bb(R) }$.
]



=== Product $sigma$-Algebras

When dealing with Cartesian products of spaces, we need a corresponding product structure for their $sigma$-algebras.

A natural question arises: for $bb(R)^n$, is the Borel $sigma$-algebra $cal(B)_(bb(R)^n)$ simply the "product" of $n$ copies of $cal(B)_(bb(R))$? The following definitions and results will show that the answer is yes.

#definition[
Let ${ (X_i , cal(F)_i) }_(i in I)$ be an indexed collection of measurable spaces (a set paired with a $sigma$-algebra). Let $X := product_(i in I) X_i$ be the Cartesian product. For each $j in I$, the #strong[coordinate map] (or projection map) is defined as:
$
pi_j : X & arrow.r X_j\
(x_i)_(i in I) & mapsto x_j.
$
The #strong[product $sigma$-algebra] on $X$, denoted $times.circle.big_(i in I) cal(F)_i$, is the $sigma$-algebra generated by the preimages of measurable sets under the coordinate maps. These generating sets, of the form $pi_i^(- 1) (E_i)$, are called #strong[cylinder sets];:
$ times.circle.big_(i in I) cal(F)_i := sigma (union.big_(i in I) { pi_i^(- 1) (E_i) : E_i in cal(F)_i }). $
]

For a countable index set $I$, a cylinder set $pi_i^(- 1) (E_i)$ with base $E_i in cal(F)_i$ can be visualized as:$ pi_i^(- 1) (E_i) = X_1 times dots.h times X_(i - 1) times E_i times X_(i + 1) times dots.h $

#proposition[
If the index set $I$ is countable, the product $sigma$-algebra is also generated by the collection of measurable "rectangles". $ times.circle.big_(i in I) cal(F)_i = sigma {product_(i in I) E_i : E_i in cal(F)_i "for all" i in I}. $
]

#proof[
Let $cal(C)_("cyl") = union.big_(i in I) { pi_i^(- 1) (E_i) : E_i in cal(F)_i }$ be the collection of cylinder sets, and let $cal(C)_("rect") = { product_(i in I) E_i : E_i in cal(F)_i }$ be the collection of measurable rectangles. We want to show $sigma (cal(C)_("cyl")) = sigma (cal(C)_("rect"))$.

- $sigma (cal(C)_("cyl")) supset.eq sigma (cal(C)_("rect"))$: Any measurable rectangle can be written as an interinterion of cylinder sets: $product_(i in I) E_i = inter.big_(i in I) pi_i^(- 1) (E_i)$. Since $I$ is countable and each $pi_i^(- 1) (E_i) in cal(C)_("cyl") subset.eq sigma (cal(C)_("cyl"))$, this countable interinterion must also be in $sigma (cal(C)_("cyl"))$. Thus, $cal(C)_("rect") subset.eq sigma (cal(C)_("cyl"))$, which implies $sigma (cal(C)_("rect")) subset.eq sigma (cal(C)_("cyl"))$.

- $sigma (cal(C)_("cyl")) subset.eq sigma (cal(C)_("rect"))$: Any cylinder set $pi_j^(- 1) (E_j)$ for some $j in I$ and $E_j in cal(F)_j$ can be written as a measurable rectangle $product_(i in I) A_i$ where $A_j = E_j$ and $A_i = X_i$ for all $i eq.not j$. Thus, $pi_j^(- 1) (E_j) in cal(C)_("rect")$. This shows that $cal(C)_("cyl") subset.eq cal(C)_("rect") subset.eq sigma (cal(C)_("rect"))$, which implies $sigma (cal(C)_("cyl")) subset.eq sigma (cal(C)_("rect"))$. Hence, the two $sigma$-algebras are equal.
]

#proposition[
Let $cal(F)_i = sigma (cal(E)_i)$ for each $i in I$. Then the product $sigma$-algebra is generated by the cylinder sets with bases in $cal(E)_i$. $ times.circle.big_(i in I) cal(F)_i = sigma (hat(cal(E))) , quad "where" hat(cal(E)) = union.big_(i in I) { pi_i^(- 1) (E_i) : E_i in cal(E)_i }. $
]

#proof[
The inclusion $sigma (hat(cal(E))) subset.eq times.circle.big_(i in I) cal(F)_i$ is clear, since each $E_i in cal(E)_i$ is also in $cal(F)_i$, meaning $hat(cal(E))$ is a sub-collection of the generating sets for $times.circle.big_(i in I) cal(F)_i$.

For the reverse inclusion, fix an index $i in I$ and consider the collection of sets:
$ cal(G)_i := { A subset.eq X_i : pi_i^(- 1) (A) in sigma (hat(cal(E))) }. $
One can verify that $cal(G)_i$ is a $sigma$-algebra on $X_i$. Furthermore, for any $A in cal(E)_i$, its preimage $pi_i^(- 1) (A)$ is in $hat(cal(E))$ by definition, and thus $pi_i^(- 1) (A) in sigma (hat(cal(E)))$. This means $A in cal(G)_i$. So, we have shown that $cal(E)_i subset.eq cal(G)_i$. Since $cal(G)_i$ is a $sigma$-algebra containing $cal(E)_i$, it must also contain the smallest $sigma$-algebra containing $cal(E)_i$, which is $cal(F)_i = sigma (cal(E)_i)$. Therefore, $cal(F)_i subset.eq cal(G)_i$. This implies that for any $E in cal(F)_i$, we have $pi_i^(- 1) (E) in sigma (hat(cal(E)))$. Since this holds for any $i in I$ and any $E in cal(F)_i$, the generating set for the product $sigma$-algebra is contained in $sigma (hat(cal(E)))$. Thus, $times.circle.big_(i in I) cal(F)_i subset.eq sigma (hat(cal(E)))$. The equality follows.
]


=== Borel vs. Product $sigma$-Algebras

The final results connect the product topology with the product $sigma$-algebra.

#proposition[
Let $X_1 , dots.h , X_n$ be metric spaces, and let $X = X_1 times dots.h times X_n$ be the product space equipped with the product topology. Then: $ times.circle.big_(j = 1)^n cal(B)_(X_j) subset.eq cal(B)_X $ Equality holds if each metric space $X_j$ is #strong[separable] (i.e., contains a countable dense subset).
]

#proof[
- #strong[$times.circle.big_(j = 1)^n cal(B)_(X_j) subset.eq cal(B)_X$:] The product $sigma$-algebra $times.circle.big_(j = 1)^n cal(B)_(X_j)$ is generated by cylinder sets $pi_j^(- 1) (U_j)$ where $U_j$ is an open set in $X_j$. In the product topology on $X$, the projection maps $pi_j$ are continuous. Therefore, the preimage $pi_j^(- 1) (U_j)$ of any open set $U_j$ is an open set in $X$. Since these generators are all in $cal(B)_X$ (the $sigma$-algebra of all open sets and their countable combinations), the generated $sigma$-algebra must be a subset of $cal(B)_X$.
- #strong[$times.circle.big_(j = 1)^n cal(B)_(X_j) supset.eq cal(B)_X$, assuming separability:] Suppose each $X_j$ is separable. Then its topology has a countable basis. For a metric space, we can take the collection of open balls $cal(V)_j = { ball (x_k , q) : x_k in D_j , q in bb(Q) > 0 }$, where $D_j$ is a countable dense set in $X_j$. The Borel $sigma$-algebra $cal(B)_(X_j)$ is generated by this countable basis, i.e., $cal(B)_(X_j) = sigma (cal(V)_j)$. The product topology on $X$ is generated by the basis of open rectangles $cal(V) = { product_(j = 1)^n V_j : V_j in cal(V)_j }$. This is a countable collection. Thus, $cal(B)_X = sigma (cal(V))$. Each set $product_(j = 1)^n V_j$ in this generating collection $cal(V)$ is a measurable rectangle, so it belongs to $times.circle.big_(j = 1)^n cal(B)_(X_j)$. Since all the generators of $cal(B)_X$ are in $times.circle.big_(j = 1)^n cal(B)_(X_j)$, we must have $cal(B)_X subset.eq times.circle.big_(j = 1)^n cal(B)_(X_j)$. Combining both inclusions gives the equality.
]

#corollary[
The Borel $sigma$-algebra on $bb(R)^n$ is equal to the $n$-fold product of the Borel $sigma$-algebra on $bb(R)$:
$ cal(B)_(bb(R)^n) = times.circle.big_(j = 1)^n cal(B)_(bb(R)). $
]

#proof[
This follows directly from the previous proposition, as $bb(R)$ is a separable metric space (the set of rational numbers $bb(Q)$ is a countable dense subset).
]

